apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secret-dev
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: root
  COHERE_API_KEY: ktSKEncaJ7l6NR6qesabEzJM1nQ6ChaskIklcL9o
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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